// flow-typed signature: b87ca92d6af46862c129d80a613bfc1b
// flow-typed version: <<STUB>>/js-sha512_v^0.8.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-sha512'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-sha512' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-sha512/build/sha512.min' {
  declare module.exports: any;
}

declare module 'js-sha512/src/sha512' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-sha512/build/sha512.min.js' {
  declare module.exports: $Exports<'js-sha512/build/sha512.min'>;
}
declare module 'js-sha512/src/sha512.js' {
  declare module.exports: $Exports<'js-sha512/src/sha512'>;
}
