// flow-typed signature: cae3d90fba5c29d7bbb0ae836d14981e
// flow-typed version: <<STUB>>/factom_v^0.3.6/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'factom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'factom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'factom/dist/factom-struct' {
  declare module.exports: any;
}

declare module 'factom/dist/factom' {
  declare module.exports: any;
}

declare module 'factom/src/ack' {
  declare module.exports: any;
}

declare module 'factom/src/add' {
  declare module.exports: any;
}

declare module 'factom/src/addresses' {
  declare module.exports: any;
}

declare module 'factom/src/apis-cli' {
  declare module.exports: any;
}

declare module 'factom/src/blocks' {
  declare module.exports: any;
}

declare module 'factom/src/chain' {
  declare module.exports: any;
}

declare module 'factom/src/constant' {
  declare module.exports: any;
}

declare module 'factom/src/entry' {
  declare module.exports: any;
}

declare module 'factom/src/factom-cli' {
  declare module.exports: any;
}

declare module 'factom/src/factom-struct' {
  declare module.exports: any;
}

declare module 'factom/src/factom' {
  declare module.exports: any;
}

declare module 'factom/src/get' {
  declare module.exports: any;
}

declare module 'factom/src/send' {
  declare module.exports: any;
}

declare module 'factom/src/transaction' {
  declare module.exports: any;
}

declare module 'factom/src/util' {
  declare module.exports: any;
}

declare module 'factom/src/wallet' {
  declare module.exports: any;
}

declare module 'factom/test/add.integration.spec' {
  declare module.exports: any;
}

declare module 'factom/test/addresses.unit.spec' {
  declare module.exports: any;
}

declare module 'factom/test/blocks.unit.spec' {
  declare module.exports: any;
}

declare module 'factom/test/chain.unit.spec' {
  declare module.exports: any;
}

declare module 'factom/test/entry.unit.spec' {
  declare module.exports: any;
}

declare module 'factom/test/factom-cli.integration.spec' {
  declare module.exports: any;
}

declare module 'factom/test/factom-cli.unit.spec' {
  declare module.exports: any;
}

declare module 'factom/test/get.integration.spec' {
  declare module.exports: any;
}

declare module 'factom/test/send.integration.spec' {
  declare module.exports: any;
}

declare module 'factom/test/transaction.unit.spec' {
  declare module.exports: any;
}

declare module 'factom/test/util.unit.spec' {
  declare module.exports: any;
}

declare module 'factom/test/wallet.spec' {
  declare module.exports: any;
}

declare module 'factom/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'factom/dist/factom-struct.js' {
  declare module.exports: $Exports<'factom/dist/factom-struct'>;
}
declare module 'factom/dist/factom.js' {
  declare module.exports: $Exports<'factom/dist/factom'>;
}
declare module 'factom/src/ack.js' {
  declare module.exports: $Exports<'factom/src/ack'>;
}
declare module 'factom/src/add.js' {
  declare module.exports: $Exports<'factom/src/add'>;
}
declare module 'factom/src/addresses.js' {
  declare module.exports: $Exports<'factom/src/addresses'>;
}
declare module 'factom/src/apis-cli.js' {
  declare module.exports: $Exports<'factom/src/apis-cli'>;
}
declare module 'factom/src/blocks.js' {
  declare module.exports: $Exports<'factom/src/blocks'>;
}
declare module 'factom/src/chain.js' {
  declare module.exports: $Exports<'factom/src/chain'>;
}
declare module 'factom/src/constant.js' {
  declare module.exports: $Exports<'factom/src/constant'>;
}
declare module 'factom/src/entry.js' {
  declare module.exports: $Exports<'factom/src/entry'>;
}
declare module 'factom/src/factom-cli.js' {
  declare module.exports: $Exports<'factom/src/factom-cli'>;
}
declare module 'factom/src/factom-struct.js' {
  declare module.exports: $Exports<'factom/src/factom-struct'>;
}
declare module 'factom/src/factom.js' {
  declare module.exports: $Exports<'factom/src/factom'>;
}
declare module 'factom/src/get.js' {
  declare module.exports: $Exports<'factom/src/get'>;
}
declare module 'factom/src/send.js' {
  declare module.exports: $Exports<'factom/src/send'>;
}
declare module 'factom/src/transaction.js' {
  declare module.exports: $Exports<'factom/src/transaction'>;
}
declare module 'factom/src/util.js' {
  declare module.exports: $Exports<'factom/src/util'>;
}
declare module 'factom/src/wallet.js' {
  declare module.exports: $Exports<'factom/src/wallet'>;
}
declare module 'factom/test/add.integration.spec.js' {
  declare module.exports: $Exports<'factom/test/add.integration.spec'>;
}
declare module 'factom/test/addresses.unit.spec.js' {
  declare module.exports: $Exports<'factom/test/addresses.unit.spec'>;
}
declare module 'factom/test/blocks.unit.spec.js' {
  declare module.exports: $Exports<'factom/test/blocks.unit.spec'>;
}
declare module 'factom/test/chain.unit.spec.js' {
  declare module.exports: $Exports<'factom/test/chain.unit.spec'>;
}
declare module 'factom/test/entry.unit.spec.js' {
  declare module.exports: $Exports<'factom/test/entry.unit.spec'>;
}
declare module 'factom/test/factom-cli.integration.spec.js' {
  declare module.exports: $Exports<'factom/test/factom-cli.integration.spec'>;
}
declare module 'factom/test/factom-cli.unit.spec.js' {
  declare module.exports: $Exports<'factom/test/factom-cli.unit.spec'>;
}
declare module 'factom/test/get.integration.spec.js' {
  declare module.exports: $Exports<'factom/test/get.integration.spec'>;
}
declare module 'factom/test/send.integration.spec.js' {
  declare module.exports: $Exports<'factom/test/send.integration.spec'>;
}
declare module 'factom/test/transaction.unit.spec.js' {
  declare module.exports: $Exports<'factom/test/transaction.unit.spec'>;
}
declare module 'factom/test/util.unit.spec.js' {
  declare module.exports: $Exports<'factom/test/util.unit.spec'>;
}
declare module 'factom/test/wallet.spec.js' {
  declare module.exports: $Exports<'factom/test/wallet.spec'>;
}
declare module 'factom/webpack.config.js' {
  declare module.exports: $Exports<'factom/webpack.config'>;
}
