// flow-typed signature: c0a14bb91e3e38181ee383fcc670f29a
// flow-typed version: <<STUB>>/@fat-token/fat-js_v^1.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fat-token/fat-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fat-token/fat-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fat-token/fat-js/0/CLI' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/0/Issuance' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/0/IssuanceBuilder' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/0/Transaction' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/0/TransactionBuilder' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/1/CLI' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/1/Issuance' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/1/IssuanceBuilder' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/1/Transaction' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/1/TransactionBuilder' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/cli/CLI' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/cli/compatibility' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/constant' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/dist/fatjs' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/0/0.cli.integration.spec' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/0/0.issuance.unit.spec' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/0/0.transaction.unit.spec' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/1/1.cli.integration.spec' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/1/1.issuance.unit.spec' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/1/1.transaction.unit.spec' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/cli/cli.integration.spec' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/cli/cli.unit.spec' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/constant/constant' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/test' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/test/util/util.unit.spec' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/util' {
  declare module.exports: any;
}

declare module '@fat-token/fat-js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fat-token/fat-js/0/CLI.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/0/CLI'>;
}
declare module '@fat-token/fat-js/0/Issuance.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/0/Issuance'>;
}
declare module '@fat-token/fat-js/0/IssuanceBuilder.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/0/IssuanceBuilder'>;
}
declare module '@fat-token/fat-js/0/Transaction.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/0/Transaction'>;
}
declare module '@fat-token/fat-js/0/TransactionBuilder.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/0/TransactionBuilder'>;
}
declare module '@fat-token/fat-js/1/CLI.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/1/CLI'>;
}
declare module '@fat-token/fat-js/1/Issuance.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/1/Issuance'>;
}
declare module '@fat-token/fat-js/1/IssuanceBuilder.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/1/IssuanceBuilder'>;
}
declare module '@fat-token/fat-js/1/Transaction.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/1/Transaction'>;
}
declare module '@fat-token/fat-js/1/TransactionBuilder.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/1/TransactionBuilder'>;
}
declare module '@fat-token/fat-js/cli/CLI.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/cli/CLI'>;
}
declare module '@fat-token/fat-js/cli/compatibility.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/cli/compatibility'>;
}
declare module '@fat-token/fat-js/constant.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/constant'>;
}
declare module '@fat-token/fat-js/dist/fatjs.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/dist/fatjs'>;
}
declare module '@fat-token/fat-js/index' {
  declare module.exports: $Exports<'@fat-token/fat-js'>;
}
declare module '@fat-token/fat-js/index.js' {
  declare module.exports: $Exports<'@fat-token/fat-js'>;
}
declare module '@fat-token/fat-js/test/0/0.cli.integration.spec.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/0/0.cli.integration.spec'>;
}
declare module '@fat-token/fat-js/test/0/0.issuance.unit.spec.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/0/0.issuance.unit.spec'>;
}
declare module '@fat-token/fat-js/test/0/0.transaction.unit.spec.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/0/0.transaction.unit.spec'>;
}
declare module '@fat-token/fat-js/test/1/1.cli.integration.spec.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/1/1.cli.integration.spec'>;
}
declare module '@fat-token/fat-js/test/1/1.issuance.unit.spec.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/1/1.issuance.unit.spec'>;
}
declare module '@fat-token/fat-js/test/1/1.transaction.unit.spec.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/1/1.transaction.unit.spec'>;
}
declare module '@fat-token/fat-js/test/cli/cli.integration.spec.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/cli/cli.integration.spec'>;
}
declare module '@fat-token/fat-js/test/cli/cli.unit.spec.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/cli/cli.unit.spec'>;
}
declare module '@fat-token/fat-js/test/constant/constant.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/constant/constant'>;
}
declare module '@fat-token/fat-js/test/test.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/test'>;
}
declare module '@fat-token/fat-js/test/util/util.unit.spec.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/test/util/util.unit.spec'>;
}
declare module '@fat-token/fat-js/util.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/util'>;
}
declare module '@fat-token/fat-js/webpack.config.js' {
  declare module.exports: $Exports<'@fat-token/fat-js/webpack.config'>;
}
