// flow-typed signature: f753c3765b9093cd7f5b9a1fbae18483
// flow-typed version: <<STUB>>/bip32-path_v0.4.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bip32-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bip32-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bip32-path/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bip32-path/index' {
  declare module.exports: $Exports<'bip32-path'>;
}
declare module 'bip32-path/index.js' {
  declare module.exports: $Exports<'bip32-path'>;
}
declare module 'bip32-path/test/index.js' {
  declare module.exports: $Exports<'bip32-path/test/index'>;
}
